"""create phones table with correct columns and lengths

Revision ID: 845cca99a908
Revises: 
Create Date: 2025-05-23 20:44:07.167915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845cca99a908'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('display_type', sa.String(length=255), nullable=True),
    sa.Column('screen_size_inches', sa.Float(), nullable=True),
    sa.Column('display_resolution', sa.String(length=255), nullable=True),
    sa.Column('pixel_density_ppi', sa.Integer(), nullable=True),
    sa.Column('refresh_rate_hz', sa.Integer(), nullable=True),
    sa.Column('screen_protection', sa.String(length=255), nullable=True),
    sa.Column('display_brightness', sa.String(length=255), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=255), nullable=True),
    sa.Column('hdr_support', sa.String(length=255), nullable=True),
    sa.Column('chipset', sa.String(length=512), nullable=True),
    sa.Column('cpu', sa.String(length=512), nullable=True),
    sa.Column('gpu', sa.String(length=512), nullable=True),
    sa.Column('ram', sa.String(length=255), nullable=True),
    sa.Column('ram_type', sa.String(length=255), nullable=True),
    sa.Column('internal_storage', sa.String(length=255), nullable=True),
    sa.Column('storage_type', sa.String(length=255), nullable=True),
    sa.Column('virtual_ram', sa.String(length=255), nullable=True),
    sa.Column('camera_setup', sa.String(length=512), nullable=True),
    sa.Column('primary_camera_resolution', sa.String(length=512), nullable=True),
    sa.Column('selfie_camera_resolution', sa.String(length=512), nullable=True),
    sa.Column('primary_camera_video_recording', sa.String(length=255), nullable=True),
    sa.Column('selfie_camera_video_recording', sa.String(length=255), nullable=True),
    sa.Column('primary_camera_ois', sa.String(length=255), nullable=True),
    sa.Column('primary_camera_aperture', sa.String(length=255), nullable=True),
    sa.Column('primary_camera_image_resolution', sa.String(length=255), nullable=True),
    sa.Column('selfie_camera_aperture', sa.String(length=255), nullable=True),
    sa.Column('camera_features', sa.String(length=1024), nullable=True),
    sa.Column('autofocus', sa.String(length=255), nullable=True),
    sa.Column('flash', sa.String(length=255), nullable=True),
    sa.Column('settings', sa.String(length=1024), nullable=True),
    sa.Column('zoom', sa.String(length=255), nullable=True),
    sa.Column('shooting_modes', sa.String(length=1024), nullable=True),
    sa.Column('video_fps', sa.String(length=255), nullable=True),
    sa.Column('battery_type', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.String(length=255), nullable=True),
    sa.Column('quick_charging', sa.String(length=255), nullable=True),
    sa.Column('wireless_charging', sa.String(length=255), nullable=True),
    sa.Column('reverse_charging', sa.String(length=255), nullable=True),
    sa.Column('build', sa.String(length=1024), nullable=True),
    sa.Column('weight', sa.String(length=255), nullable=True),
    sa.Column('thickness', sa.String(length=255), nullable=True),
    sa.Column('colors', sa.String(length=1024), nullable=True),
    sa.Column('waterproof', sa.String(length=255), nullable=True),
    sa.Column('ip_rating', sa.String(length=255), nullable=True),
    sa.Column('ruggedness', sa.String(length=255), nullable=True),
    sa.Column('network', sa.String(length=255), nullable=True),
    sa.Column('speed', sa.String(length=255), nullable=True),
    sa.Column('sim_slot', sa.String(length=255), nullable=True),
    sa.Column('volte', sa.String(length=255), nullable=True),
    sa.Column('bluetooth', sa.String(length=255), nullable=True),
    sa.Column('wlan', sa.String(length=1024), nullable=True),
    sa.Column('gps', sa.String(length=1024), nullable=True),
    sa.Column('nfc', sa.String(length=255), nullable=True),
    sa.Column('usb_type_c', sa.String(length=255), nullable=True),
    sa.Column('usb_otg', sa.String(length=255), nullable=True),
    sa.Column('fingerprint_sensor', sa.String(length=255), nullable=True),
    sa.Column('finger_sensor_type', sa.String(length=255), nullable=True),
    sa.Column('finger_sensor_position', sa.String(length=255), nullable=True),
    sa.Column('face_unlock', sa.String(length=255), nullable=True),
    sa.Column('light_sensor', sa.String(length=1024), nullable=True),
    sa.Column('sensor', sa.String(length=1024), nullable=True),
    sa.Column('infrared', sa.String(length=255), nullable=True),
    sa.Column('fm_radio', sa.String(length=255), nullable=True),
    sa.Column('operating_system', sa.String(length=255), nullable=True),
    sa.Column('os_version', sa.String(length=255), nullable=True),
    sa.Column('user_interface', sa.String(length=255), nullable=True),
    sa.Column('release_date', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('made_by', sa.String(length=255), nullable=True),
    sa.Column('price_per_gb_ram', sa.Float(), nullable=True),
    sa.Column('price_per_gb_storage', sa.Float(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('display_score', sa.Float(), nullable=True),
    sa.Column('camera_score', sa.Float(), nullable=True),
    sa.Column('storage_score', sa.Float(), nullable=True),
    sa.Column('battery_efficiency', sa.Float(), nullable=True),
    sa.Column('price_to_display', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phones_brand'), 'phones', ['brand'], unique=False)
    op.create_index(op.f('ix_phones_id'), 'phones', ['id'], unique=False)
    op.create_index(op.f('ix_phones_model'), 'phones', ['model'], unique=False)
    op.create_index(op.f('ix_phones_name'), 'phones', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phones_name'), table_name='phones')
    op.drop_index(op.f('ix_phones_model'), table_name='phones')
    op.drop_index(op.f('ix_phones_id'), table_name='phones')
    op.drop_index(op.f('ix_phones_brand'), table_name='phones')
    op.drop_table('phones')
    # ### end Alembic commands ###