"""upgradated table

Revision ID: a2aab67b540c
Revises: f43d9c85fed7
Create Date: 2025-05-21 16:07:19.376455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2aab67b540c'
down_revision = 'f43d9c85fed7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phones', sa.Column('primary_camera_image_resolution', sa.String(length=100), nullable=True))
    op.add_column('phones', sa.Column('autofocus', sa.String(length=255), nullable=True))
    op.add_column('phones', sa.Column('flash', sa.String(length=100), nullable=True))
    op.add_column('phones', sa.Column('settings', sa.String(length=255), nullable=True))
    op.add_column('phones', sa.Column('zoom', sa.String(length=100), nullable=True))
    op.add_column('phones', sa.Column('shooting_modes', sa.String(length=255), nullable=True))
    op.add_column('phones', sa.Column('video_fps', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phones', 'video_fps')
    op.drop_column('phones', 'shooting_modes')
    op.drop_column('phones', 'zoom')
    op.drop_column('phones', 'settings')
    op.drop_column('phones', 'flash')
    op.drop_column('phones', 'autofocus')
    op.drop_column('phones', 'primary_camera_image_resolution')
    # ### end Alembic commands ###