/**
 * Utility functions for exporting comparison data and sharing
 */

import { Phone } from '../api/phones';

/**
 * Generate PDF content for phone comparison
 * Note: This is a simplified implementation. For production, consider using libraries like jsPDF or Puppeteer
 */
export function generateComparisonPDF(phones: Phone[], verdict?: string): Promise<void> {
  return new Promise((resolve, reject) => {
    try {
      // Create a new window with the comparison content
      const printWindow = window.open('', '_blank');
      
      if (!printWindow) {
        throw new Error('Unable to open print window. Please check your popup blocker settings.');
      }

      const htmlContent = generatePrintableHTML(phones, verdict);
      
      printWindow.document.write(htmlContent);
      printWindow.document.close();
      
      // Wait for content to load, then trigger print
      printWindow.onload = () => {
        setTimeout(() => {
          printWindow.print();
          printWindow.close();
          resolve();
        }, 500);
      };
      
    } catch (error) {
      console.error('Error generating PDF:', error);
      reject(error);
    }
  });
}

/**
 * Generate HTML content for printing/PDF export
 */
function generatePrintableHTML(phones: Phone[], verdict?: string): string {
  const phoneRows = phones.map(phone => `
    <div class="phone-card">
      <img src="${phone.img_url || 'https://via.placeholder.com/150x200?text=No+Image'}" alt="${phone.name}" style="width: 100px; height: 130px; object-fit: contain;">
      <h3>${phone.brand} ${phone.name}</h3>
      <p class="price">Tk. ${phone.price}</p>
      <div class="specs">
        <p><strong>RAM:</strong> ${phone.ram_gb ? `${phone.ram_gb}GB` : 'N/A'}</p>
        <p><strong>Storage:</strong> ${phone.storage_gb ? `${phone.storage_gb}GB` : 'N/A'}</p>
        <p><strong>Camera:</strong> ${phone.primary_camera_mp ? `${phone.primary_camera_mp}MP` : 'N/A'}</p>
        <p><strong>Battery:</strong> ${phone.battery_capacity_numeric ? `${phone.battery_capacity_numeric}mAh` : 'N/A'}</p>
        <p><strong>Display:</strong> ${phone.screen_size_inches ? `${phone.screen_size_inches}"` : 'N/A'}</p>
      </div>
    </div>
  `).join('');

  const verdictSection = verdict ? `
    <div class="verdict-section">
      <h2>AI Verdict</h2>
      <div class="verdict-content">
        ${verdict.split('\n').map(line => `<p>${line}</p>`).join('')}
      </div>
    </div>
  ` : '';

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Phone Comparison - Epick</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 20px;
          color: #333;
        }
        .header {
          text-align: center;
          margin-bottom: 30px;
          border-bottom: 2px solid #2d5016;
          padding-bottom: 20px;
        }
        .header h1 {
          color: #2d5016;
          margin: 0;
        }
        .header p {
          color: #666;
          margin: 5px 0 0 0;
        }
        .phones-container {
          display: flex;
          flex-wrap: wrap;
          gap: 20px;
          justify-content: center;
          margin-bottom: 30px;
        }
        .phone-card {
          border: 1px solid #ddd;
          border-radius: 8px;
          padding: 15px;
          text-align: center;
          width: 200px;
          background: #f9f9f9;
        }
        .phone-card img {
          border-radius: 4px;
          margin-bottom: 10px;
        }
        .phone-card h3 {
          margin: 10px 0 5px 0;
          color: #2d5016;
          font-size: 16px;
        }
        .price {
          font-weight: bold;
          color: #2d5016;
          font-size: 18px;
          margin: 5px 0 15px 0;
        }
        .specs {
          text-align: left;
        }
        .specs p {
          margin: 5px 0;
          font-size: 14px;
        }
        .verdict-section {
          margin-top: 30px;
          padding: 20px;
          background: #f0f8f0;
          border-radius: 8px;
          border-left: 4px solid #2d5016;
        }
        .verdict-section h2 {
          color: #2d5016;
          margin-top: 0;
        }
        .verdict-content p {
          line-height: 1.6;
          margin: 10px 0;
        }
        .footer {
          margin-top: 30px;
          text-align: center;
          font-size: 12px;
          color: #666;
          border-top: 1px solid #ddd;
          padding-top: 15px;
        }
        @media print {
          body { margin: 0; }
          .phone-card { break-inside: avoid; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Phone Comparison</h1>
        <p>Generated by Epick - Your AI-Powered Phone Assistant</p>
        <p>Date: ${new Date().toLocaleDateString()}</p>
      </div>
      
      <div class="phones-container">
        ${phoneRows}
      </div>
      
      ${verdictSection}
      
      <div class="footer">
        <p>This comparison was generated by Epick AI. Please verify specifications and prices before making a purchase decision.</p>
        <p>Visit us at epick.com.bd for more phone comparisons and recommendations.</p>
      </div>
    </body>
    </html>
  `;
}

/**
 * Generate shareable URL for comparison
 */
export function generateShareableUrl(phoneIds: number[], baseUrl: string = window.location.origin): string {
  const path = `/compare/${phoneIds.join('-')}`;
  return `${baseUrl}${path}`;
}

/**
 * Copy text to clipboard
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text);
      return true;
    } else {
      // Fallback for older browsers
      const textArea = document.createElement('textarea');
      textArea.value = text;
      textArea.style.position = 'fixed';
      textArea.style.left = '-999999px';
      textArea.style.top = '-999999px';
      document.body.appendChild(textArea);
      textArea.focus();
      textArea.select();
      
      const result = document.execCommand('copy');
      document.body.removeChild(textArea);
      return result;
    }
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}

/**
 * Share comparison via Web Share API (if supported)
 */
export async function shareComparison(phones: Phone[], url: string): Promise<boolean> {
  if (!navigator.share) {
    return false;
  }

  try {
    const phoneNames = phones.map(p => `${p.brand} ${p.name}`).join(' vs ');
    
    await navigator.share({
      title: `Phone Comparison: ${phoneNames}`,
      text: `Check out this phone comparison on Epick: ${phoneNames}`,
      url: url
    });
    
    return true;
  } catch (error) {
    console.error('Error sharing:', error);
    return false;
  }
}

/**
 * Comparison history management
 */
export interface ComparisonHistoryItem {
  id: string;
  phoneIds: number[];
  phoneNames: string[];
  timestamp: Date;
  url: string;
}

const HISTORY_STORAGE_KEY = 'epick_comparison_history';
const MAX_HISTORY_ITEMS = 10;

/**
 * Save comparison to history
 */
export function saveComparisonToHistory(phones: Phone[]): void {
  try {
    const historyItem: ComparisonHistoryItem = {
      id: Date.now().toString(),
      phoneIds: phones.map(p => p.id),
      phoneNames: phones.map(p => `${p.brand} ${p.name}`),
      timestamp: new Date(),
      url: generateShareableUrl(phones.map(p => p.id))
    };

    const existingHistory = getComparisonHistory();
    
    // Remove duplicate if exists (same phone combination)
    const filteredHistory = existingHistory.filter(item => 
      !arraysEqual(item.phoneIds.sort(), historyItem.phoneIds.sort())
    );

    // Add new item to beginning
    const newHistory = [historyItem, ...filteredHistory].slice(0, MAX_HISTORY_ITEMS);
    
    localStorage.setItem(HISTORY_STORAGE_KEY, JSON.stringify(newHistory));
  } catch (error) {
    console.error('Error saving comparison to history:', error);
  }
}

/**
 * Get comparison history
 */
export function getComparisonHistory(): ComparisonHistoryItem[] {
  try {
    const historyJson = localStorage.getItem(HISTORY_STORAGE_KEY);
    if (!historyJson) return [];

    const history = JSON.parse(historyJson);
    
    // Convert timestamp strings back to Date objects
    return history.map((item: any) => ({
      ...item,
      timestamp: new Date(item.timestamp)
    }));
  } catch (error) {
    console.error('Error loading comparison history:', error);
    return [];
  }
}

/**
 * Clear comparison history
 */
export function clearComparisonHistory(): void {
  try {
    localStorage.removeItem(HISTORY_STORAGE_KEY);
  } catch (error) {
    console.error('Error clearing comparison history:', error);
  }
}

/**
 * Helper function to compare arrays
 */
function arraysEqual(a: number[], b: number[]): boolean {
  if (a.length !== b.length) return false;
  return a.every((val, index) => val === b[index]);
}